export enum UserRole {
  USER = "user",
  ADMIN = "admin",
}

export enum AuthErrorCode {
  INVALID_ORIGIN = "INVALID_ORIGIN",
  FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
}
